### ISSUE TITLE
Fix credits crash

### ISSUE THREAD

**Issue by thecozies** [Reonu/HackerSM64#108] opened 2021-12-11 22:09 UTC

**Comment by Mr-Wiseguy** [comment] 2021-12-13 21:24
I will be taking a look at this.

**Comment by Mr-Wiseguy** [comment] 2021-12-13 23:38
This crash is not caused by the credits itself, but rather by something in Rainbow Ride. Loading into the level itself also crashes. I'm going to try removing objects to see if any specific one is causing it.

**Comment by Mr-Wiseguy** [comment] 2021-12-13 23:58
The crash was caused by sliding platform bparams being wrong. This was fixed by https://github.com/Reonu/HackerSM64/pull/139/

**Closed by Mr-Wiseguy** 2021-12-13 23:58 UTC
Labels: bug
