### ISSUE TITLE
Penguin race sometimes cant be completed

### ISSUE THREAD

**Issue by thecozies** [Reonu/HackerSM64#259] opened 2021-12-29 00:33 UTC
Intermittent issue, goes back past the initial develop/refactor commit. Should probably bisect from #85

**Comment by gheskett** [comment] 2021-12-29 07:45
This now seems to happen every single time when it formerly never happened during my testing of the refactor. This likely means the issue (if not new) has been worsened within the last few days. Because of this, I'm moving this issue back to 2.0.

**Comment by axollyon** [comment] 2021-12-29 07:58
At the very least, I can confirm that this didn't occur on December 15, with `ENABLE_VANILLA_LEVEL_SPECIFIC_CHECKS` enabled (if relevant).

**Comment by gheskett** [comment] 2021-12-29 08:01
Confirmed to happen on console as well, in case there were any doubts over platform.

**Comment by axollyon** [comment] 2021-12-29 08:09
look him go
https://user-images.githubusercontent.com/20480418/147640734-e73cdd5b-5e18-48d1-8dee-fe98ae986342.mp4

**Closed** 2021-12-29 19:06 UTC
Labels: bug
