### ISSUE TITLE
Disabling CLEAR_RAM causes an immediate crash

### ISSUE THREAD

**Issue by thecozies** [Reonu/HackerSM64#189] opened 2021-12-17 14:44 UTC
Game will start with WOOOAAAAWWWW, but black screen and no crash screen.

**Comment by gheskett** [comment] 2021-12-17 14:47
This could basically be caused by _anything_. Might be better to push off for a 2.1 release for now if a fix isn't easily determinable.

**Comment by thecozies** [comment] 2021-12-17 15:47
i agree, though if this is a severe enough issue it could be worth a 2.0.1 release

**Comment by Mr-Wiseguy** [comment] 2021-12-18 05:41
This is caused by BSS for segments besides main not being properly cleared on boot. It's not really a big deal to leave this on with that in mind, as the alternative would just be zeroing out the memory for each segment's BSS.

**Comment by Mr-Wiseguy** [comment] 2022-01-17 05:43
Fixed by #297

**Closed by Mr-Wiseguy** 2022-01-17 05:43 UTC
Labels: bug, waiting on pull request
